version: "2" # required to adjust maintainability checks

checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 95
  identical-code:
    config:
      threshold: 95
exclude_patterns:
  - "**/node_modules/"
  - "**/dist"
  - "**/test"
  - "**/lib"
  - "**/*.d.ts"
